// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe7dQmey3qWVsvpTvfhivU4qQHzxt09I4',
    appId: '1:511393830464:web:f66e7f490210f09ebcf1a5',
    messagingSenderId: '511393830464',
    projectId: 'app-builder-hackathon-f1b7b',
    authDomain: 'app-builder-hackathon-f1b7b.firebaseapp.com',
    storageBucket: 'app-builder-hackathon-f1b7b.firebasestorage.app',
    measurementId: 'G-ME8JWRCMXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiwV5iykTtbvE6Qj-uUV3PzR2p987UbI',
    appId: '1:511393830464:android:4885764b44304756bcf1a5',
    messagingSenderId: '511393830464',
    projectId: 'app-builder-hackathon-f1b7b',
    storageBucket: 'app-builder-hackathon-f1b7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASfhPmHpJ04ZBER9VRWqKMsQZ-_fOoUz4',
    appId: '1:511393830464:ios:4097330a515c4d6ebcf1a5',
    messagingSenderId: '511393830464',
    projectId: 'app-builder-hackathon-f1b7b',
    storageBucket: 'app-builder-hackathon-f1b7b.firebasestorage.app',
    iosBundleId: 'com.gerardosison.appBuilderHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASfhPmHpJ04ZBER9VRWqKMsQZ-_fOoUz4',
    appId: '1:511393830464:ios:4097330a515c4d6ebcf1a5',
    messagingSenderId: '511393830464',
    projectId: 'app-builder-hackathon-f1b7b',
    storageBucket: 'app-builder-hackathon-f1b7b.firebasestorage.app',
    iosBundleId: 'com.gerardosison.appBuilderHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe7dQmey3qWVsvpTvfhivU4qQHzxt09I4',
    appId: '1:511393830464:web:f0eea931e7299236bcf1a5',
    messagingSenderId: '511393830464',
    projectId: 'app-builder-hackathon-f1b7b',
    authDomain: 'app-builder-hackathon-f1b7b.firebaseapp.com',
    storageBucket: 'app-builder-hackathon-f1b7b.firebasestorage.app',
    measurementId: 'G-YN78ZB14EP',
  );
}
